# Generated by Django 4.0.1 on 2023-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('mlanguage', models.CharField(max_length=30)),
                ('mdescription', models.CharField(max_length=30)),
                ('mfile', models.FileField(upload_to='profile/')),
            ],
        ),
    ]
