# Generated by Django 4.0.1 on 2023-08-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieup',
            old_name='mfile',
            new_name='mvideo',
        ),
    ]
