# Generated by Django 4.0.1 on 2023-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_rename_mfile_movieup_mvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieup',
            name='mpic',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieup',
            name='mvideo',
            field=models.FileField(upload_to='video/'),
        ),
    ]
