# Generated by Django 4.0.1 on 2023-08-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_alter_usersubscription_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='expiry_date',
        ),
    ]
